---
title: Coast wise
baseurl: "/"
permalink: "/:title/"
palette: blue
header:
  title: Coastwise.nz
  tagline: A future that actually make sense
  logo_img: "/images/coastwise.png"
  bg_img: "/images/Greymouth.jpg"
  has_nav: true
  has_social: true
footer:
  content: "&copy; Stackbit-Fjord. All rights reserved."
  links:
  - new_window: true
  - text: Made with Stackbit
    url: https://www.stackbit.com
    new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
collections:
  posts:
    permalink: "/posts/:title/"
menu:
  main:
    title: About
    weight: 2
